version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/<DATABASE_NAME>
      - SPRING_DATASOURCE_USERNAME=<DATABASE_USERNAME>
      - SPRING_DATASOURCE_PASSWORD=<DATABASE_PASSWORD>
  postgres_db:
    image: "postgres"
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./resources/scripts/init.sql:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: <DATABASE_PASSWORD>
      POSTGRES_USER: <DATABASE_USERNAME>
      POSTGRES_DB: <DATABASE_NAME>
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"